dist: trusty
sudo: required

language: cpp
cache: ccache

branches:
  only:
  - master
  - develop

before_install:
 - sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu/ xenial main universe' -y
 - sudo sh -c "echo deb-src http://archive.ubuntu.com/ubuntu/ xenial main universe \ >> /etc/apt/sources.list"
 - sudo apt-get update -qq

install:
  - sudo apt-get -qq install libboost-filesystem-dev libglew-dev libglm-dev libfreeimage-dev libassimp-dev libfreetype6-dev libglfw3-dev
  - sudo apt-get -qq install --only-upgrade cmake clang gcc g++

compiler:
  - gcc

before_script:
  - cmake .

script: make
