language: cpp

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libglew-dev libglm-dev libboost-filesystem-dev libfreeimage-dev libassimp-dev libfreetype6-dev libglfw3-dev

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
