language: cpp

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y upgrade cmake
  - sudo apt-get install -y libglew-dev
  - sudo apt-get install -y libglm-dev
  - sudo apt-get install -y libboost-filesystem-dev
  - sudo apt-get install -y libfreeimage-dev
  - sudo apt-get install -y libassimp-dev
  - sudo apt-get install -y libfreetype6-dev
# GLFW 3.2.1 install
  - wget -O glfw-3.2.1.zip https://github.com/glfw/glfw/archive/3.2.1.zip
  - unzip glfw-3.2.1.zip
  - cd glfw-3.2.1
  - cmake -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=/x86_64-linux-gnu
  - make
  - sudo make install

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
