sudo: required
dist: xenial

language: cpp

branches:
  only:
   - master
   - develop

addons:
  apt:
    sources:
      - sourceline: 'deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe'
      - sourceline: 'deb-src http://us.archive.ubuntu.com/ubuntu/ xenial main universe'
    packages:
      - libboost-filesystem-dev
      - libglew-dev
      - libglm-dev
      - libfreeimage-dev
      - libassimp-dev
      - libfreetype6-dev
      - libglfw3-dev

install:
  - sudo apt-get -qq update
  - sudo apt-get install --only-upgrade cmake clang gcc g++

compiler:
  - gcc

before_script:
  - cmake .

script: make
