# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

language: cpp

addons:
  apt:
    packages:
      - libglew-dev
      - libglm-dev
      - libboost-filesystem-dev
      - libfreeimage-dev
      - libassimp-dev
      - libfreetype6-dev
      - libglfw3-dev

compiler:
  - gcc

before_script:
  - cmake .

script: make
