sudo: required
dist: wily

language: cpp

branches:
  only:
   - master
   - develop

addons:
  apt:
    packages:
      - libglew-dev
      - libboost-filesystem-dev
      - libglm-dev
      - libfreeimage-dev
      - libassimp-dev
      - libfreetype6-dev

compiler:
  - gcc

before_script:
  - cmake .

script: make
