language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - libglew-dev
      - libglm-dev
      - libboost-filesystem-dev
      - libfreeimage-dev
      - libassimp-dev
      - libfreetype6-dev

before_install:
# GLFW 3.2.1 install
  - wget -O glfw-3.2.1.zip https://github.com/glfw/glfw/archive/3.2.1.zip
  - unzip glfw-3.2.1.zip
  - cd glfw-3.2.1
  - cmake -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=/x86_64-linux-gnu
  - make
  - sudo make install

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
