language: cpp

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libglew-dev
  - sudo apt-get install -y libglm-dev
  - sudo apt-get install -y libboost-filesystem-dev
  - sudo apt-get install -y libfreeimage-dev
  - sudo apt-get install -y libassimp-dev
  - sudo apt-get install -y libfreetype6-dev
  - sudo apt-get install -y libglfw3-dev

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
