language: cpp

branches:
  only:
   - master
   - develop

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
      - cmake
      - cmake-data
      - libglm-dev
      - libfreeimage-dev
      - libassimp-dev
      - libfreetype6-dev

before_install:
  - sudo add-apt-repository ppa:apokluda/boost1.53 --yes
  - sudo apt-get update
# GLFW 3.2.1 install
  - wget -O glfw-3.2.1.zip https://github.com/glfw/glfw/archive/3.2.1.zip
  - unzip glfw-3.2.1.zip
  - cd glfw-3.2.1
  - cmake -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=/x86_64-linux-gnu
  - make
  - sudo make install
  - cd ..
# GLEW 1.13.0 install
  - wget -O glew-1.13.0.zip https://github.com/nigels-com/glew/archive/glew-1.13.0.zip
  - unzip glew-1.13.0.zip
  - cd glew-glew-1.13.0
  - make extensions
  - make
  - sudo make install
  - cd ..

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - sudo apt-get install libboost-filesystem1.53-dev

compiler:
  - gcc

before_script:
  - cmake .

script: make
