sudo: required
dist: xenial

language: cpp

branches:
  only:
   - master
   - develop

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://us.archive.ubuntu.com/ubuntu/ xenial main'
      - sourceline: 'deb-src http://us.archive.ubuntu.com/ubuntu/ xenial main'
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
      - libboost-filesystem-dev
      - libglew-dev
      - libglm-dev
      - libfreeimage-dev
      - libassimp-dev
      - libfreetype6-dev

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

compiler:
  - gcc

before_script:
  - cmake .

script: make
