#ifndef LOCATIONS_GLSL
#define LOCATIONS_GLSL

// geometry pass:
#define MATERIAL_DIFFUSE_BINDING 0
#define MATERIAL_SPECULAR_BINDING 1
#define MATERIAL_NORMAL_BINDING 2
#define MATERIAL_DISPLACEMENT_BINDING 3
#define MATERIAL_OPACITY_BINDING 4

// lighting pass
#define DEFERRED_ALBEDO_BINDING 0
#define DEFERRED_SPECULAR_BINDING 1
#define DEFERRED_NORMAL_BINDING 2
#define DEFERRED_POSITION_BINDING 3
#define DEFERRED_SSAO_NOISE_BINDING 4
#define DEFERRED_SSAO_BINDING 4

// post-processing passes
#define FILTER_COLOR_TEXTURE
#define FILTER_BLOOM_TEXTURE

#endif /* LOCATIONS_GLSL */
