#ifndef BINDINGS_GLSL
#define BINDINGS_GLSL

// buffers
#define BUFFER_MATERIAL_BINDING 0
#define BUFFER_MATRICES_BINDING 1
#define BUFFER_CAMERA_BINDING 2
#define BUFFER_BASIC_MATERIAL_BINDING 3
#define BUFFER_DIRECTIONAL_LIGHT_BINDING 4
#define BUFFER_POINT_LIGHT_BINDING 5
#define BUFFER_SPOT_LIGHT_BINDING 6
#define BUFFER_SHADOW_CAMERA_BINDING 7

// geometry pass
#define MATERIAL_DIFFUSE_BINDING 0
#define MATERIAL_SPECULAR_BINDING 1
#define MATERIAL_NORMAL_BINDING 2
#define MATERIAL_DISPLACEMENT_BINDING 3
#define MATERIAL_OPACITY_BINDING 4

// lighting pass
#define DEFERRED_ALBEDO_BINDING 0
#define DEFERRED_SPECULAR_BINDING 1
#define DEFERRED_NORMAL_BINDING 2
#define DEFERRED_POSITION_BINDING 3
#define DEFERRED_SSAO_NOISE_BINDING 4
#define DEFERRED_SSAO_BINDING 4

// post-processing passes
#define POST_PROCESSING_COLOR_TEXTURE 0
#define POST_PROCESSING_BLOOM_COLOR_TEXTURE 1
#define POST_PROCESSING_BLOOM_TEXTURE 0

#endif /* BINDINGS_GLSL */
