#ifndef LOCATIONS_GLSL
#define LOCATIONS_GLSL

// deferred
#define DEFERRED_GBUFFER_POSITION 0
#define DEFERRED_GBUFFER_NORMAL 1
#define DEFERRED_GBUFFER_TEXTURE_COORD 2
#define DEFERRED_GBUFFER_TANGENT 3
#define DEFERRED_GBUFFER_BI_TANGENT 4

#endif /* LOCATIONS_GLSL */
